version: '3'

services:
  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always
    depends_on:
      - mongo

  graylog:
    image: graylog/graylog:3.3
    container_name: graylog
    ports:
      - 9000:9000
      - 12201:12201
      - 1514:1514
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongo
      - elasticsearch
    volumes:
      - graylog_data:/usr/share/graylog/data
    restart: always
    depends_on:
      - elasticsearch
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs
    command: filebeat -e -strict.perms=false
    restart: always  
    links:
      - graylog
    depends_on:
      - graylog

volumes:
  mongo_data:
  elasticsearch_data:
  graylog_data: